name = "worker-name"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[wrangler]
name = "wrangler"
compatibility_date = "2023-03-21"
main = "src/index.ts"

[build]
command = "yarn build"
[build.upload]
format = "service-worker"