name = "unofficial-glastonbury-2025"
main = "worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "unofficial-glastonbury-2025"

[env.staging]
name = "unofficial-glastonbury-2025-staging"

# Build configuration
[build]
command = "npm run build:client"

# Environment variables
[vars]
NODE_ENV = "production"

# Assets configuration for static files
[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"