name = "unofficial-glastonbury-2025"
main = "dist/worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "unofficial-glastonbury-2025"

[env.staging]
name = "unofficial-glastonbury-2025-staging"

[build]
command = "npm run build:worker"
cwd "./"

[vars]
NODE_ENV = "production"

[site]
bucket = ".dist/client"
entry-point = "workers-site"

# Routes
[[rules]]
type = "Rule"
globs = ["*/api/*"]
script =  "unofficial-glastonbury-2025"

[[rules]]
type = "Rule"
globs = ["*"]
script = "unofficial-glastonbury-2025"
